chore: setup local environment using firebase emulators
blueprinthub/blueprint pull request #43
Opened 2023-10-30 22:33 UTC by yarn-rp

## Description
Unify both repositories on the same one, and setups local environment using firebase emulators. 

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

2023-11-02 19:33 UTC, jvaldesgonzalez requested changes

2023-11-02 19:33 UTC, jvaldesgonzalez commented on README.md
> +npm install
suggestion: yarn is recommended

2023-11-02 19:33 UTC, jvaldesgonzalez commented on README.md
> +npm install
also `yarn install` must be executed inside functions folder

2023-11-02 19:33 UTC, jvaldesgonzalez commented on README.md
suggestion: isn't clear that we must copy local.env to .env. Add "run command `cp local.env .env` inside functions folder", or add command to the yarn script

2023-11-02 19:33 UTC, jvaldesgonzalez commented on README.md
> +- **Node.js** runtime environment (version 8 or higher)
this is outdated, the recommended node version is 16.x.x

2023-11-02 19:33 UTC, jvaldesgonzalez commented on functions/scripts/seed.ts
> +const firebaseConfigPath = path.join("./../", "firebase.json"); // adjust the path as needed
suggestion(non-blocking): this isn't the right way, add "resolveJsonModule": true into compilerOptions in tsconfig file. Then use the normal import syntax

2023-11-03 01:19 UTC, yarn-rp commented on functions/scripts/seed.ts
> +const firebaseConfigPath = path.join("./../", "firebase.json"); // adjust the path as needed
I didn't like it either, but didn't want to mess that much with the config. Glad to know that there is a better non ugly way.

2023-11-03 01:20 UTC, yarn-rp commented on README.md
> +- **Node.js** runtime environment (version 8 or higher)
noted

2023-11-03 01:21 UTC, yarn-rp commented on README.md
> +npm install
thanks for spotting the wrong directory!

2023-11-03 01:23 UTC, yarn-rp commented on README.md
Yeah, I missed this step. Thanks for noticing it.

2023-11-03 01:29 UTC, yarn-rp commented on README.md
Let me know if thats clear enough or if you wanna add something to it

2023-11-03 18:33 UTC, jvaldesgonzalez approved these changes

2023-11-03 18:33 UTC, jvaldesgonzalez commented on functions/scripts/seed.ts
>  const LOCALHOST = "localhost";
nit: change LOCALHOST to simply HOST

2023-11-03 18:34 UTC, jvaldesgonzalez commented on README.md
Seems great!

2023-11-03 18:37 UTC, merged