style: building taskcard and itemtile ui components
blueprinthub/blueprint pull request #44
Opened 2023-10-31 18:00 UTC by DavidZZGi

## Description

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-11-01 12:59 UTC, yarn-rp requested changes
Nice additions, but it's very hard for me to see if these widgets are ok or not. This is exactly why the storybook is nice, but since we don't have it, would you mind to upload screenshoots of the widgets with the name, so it's easier to see if they are right or not.

Also when doing Paddings and Margins, lets try to use `AppSpacing` class to define the sizes instead of using raw values. Related to this, kinda curious what are you doing to set the margin and the padding? Is this generated from Figma?

2023-11-01 12:59 UTC, yarn-rp commented on packages/app_ui/lib/src/widgets/priority_widget.dart
> +      backgroundColor: Theme.of(context).colorScheme.primary.withOpacity(0.3),
let'c create a variable with the `final theme = Theme.of(context);` at the top en reuse that theme on the widget

2023-11-01 13:01 UTC, yarn-rp commented on packages/app_ui/lib/src/widgets/item_tile.dart
> +    // ignore: use_colored_box
Don't ignore linter rules if not necessary

2023-11-02 13:05 UTC, DavidZZGi commented
<img width="1440" alt="Screenshot TaskCard" src="https://github.com/blueprinthub/blueprint/assets/97356065/26216d09-b0c6-4b56-b218-a2a3935dad59">
<img width="1440" alt="Screenshot 2023-11-02 at 8 40 06 AM" src="https://github.com/blueprinthub/blueprint/assets/97356065/626daca5-b360-4f57-a739-7b4d35b75722">

2023-11-20 23:54 UTC, closed without merging