feat/authentication screen
blueprinthub/blueprint pull request #49
Opened 2023-11-20 23:43 UTC by DavidZZGi

## Description

## Type of Change

- [x] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [ ] 🗑️ Chore

2023-11-21 13:14 UTC, yarn-rp requested changes
Please let me know if you need more clarification on these comments. We could always sync via slack if something is not clear

2023-11-21 13:14 UTC, yarn-rp commented on lib/app/routes/router/app_router.gr.dart
> +        child: NewSignInPage(
This is an autogenerated file, it says do not modify by hand on the top file. If you want to change a route, you do it on the `app_router.dart`. If you have any questions about this, please share it on slack. We'll be very happy to answer your questions

2023-11-21 13:14 UTC, yarn-rp commented on lib/authentication/presentation/new_sign_in.dart
> +                      const Text("Don't have an account?"),
We are going to start using `l10n` for localized text. Although English is the primary language to support, the app currently supports `en` and `es` as languages. We could stick to english on both files if we don't want to take care of the translations now, so you could fill the same texts on both files. If you have some doubts you can read the [documentation](https://docs.flutter.dev/ui/accessibility-and-internationalization/internationalization) or ask me via slack

2023-11-21 13:14 UTC, yarn-rp commented on lib/authentication/presentation/new_sign_in.dart
> +                        width: MediaQuery.of(context).size.width * 0.3,
This is no longer the optimal way to do this. With latest flutter versions, you can do 
`MediaQuery.sizeOf(context)` which is way better in terms of performance. 

To help with reutilization, usually you should compute all the context dependent variables at the top of the method, that way you don't get a new instance for everything you are going to use

2023-11-21 13:21 UTC, DavidZZGi commented on lib/authentication/presentation/new_sign_in.dart
> +class NewSignInPage extends StatelessWidget {
yep, that's i was asking yesterday, i think removing the old ones and change the prefix of the new ones

2023-11-21 13:21 UTC, DavidZZGi commented on lib/app/routes/router/app_router.gr.dart
> +        child: NewSignInPage(
ok

2023-11-21 13:22 UTC, DavidZZGi commented on lib/authentication/presentation/new_sign_in.dart
> +                        width: MediaQuery.of(context).size.width * 0.3,
ok

2023-11-21 20:50 UTC, yarn-rp requested changes

2023-11-21 20:50 UTC, yarn-rp commented on lib/authentication/presentation/pages/sign_in_page.dart
> +    final lang = AppLocalizations.of(context);
nit: very dummy change, but usually this variable is named `l10n`.  

pdf: l10n means localization, it's like l(ocalizatio=10 chars)n

2023-11-21 20:50 UTC, yarn-rp commented on lib/authentication/presentation/pages/sign_in_page.dart
> +                      Text(lang.do_not_have_account),
the recommended naming convention is PascalCase, not snake case. See the example counter title. Also it's always nice to add the description to help with ambiguity

2023-11-21 20:50 UTC, yarn-rp commented on lib/core/l10n/arb/app_es.arb
> +    "do_not_have_account":"No tienes una cuenta?",
I would prefer to leave this all in english, that way we don't waste time. Just use the same message we used on the `app_en` counterpart and good to go.

2023-11-21 20:50 UTC, yarn-rp commented on lib/core/l10n/arb/app_en.arb
> +    "forget_pass":"Forget Password",
this should be forgot password I think, not forget.

2023-11-22 14:43 UTC, yarn-rp requested changes

2023-11-22 14:43 UTC, yarn-rp commented on firebase.json
I thought we agreed on not including changes on this file. Why are we still seeing this?

2023-11-22 14:43 UTC, yarn-rp commented on lib/authentication/presentation/pages/sign_in_page.dart
> +                padding: const EdgeInsets.all(16),
Use `AppSpacings` for paddings too

2023-11-22 14:43 UTC, yarn-rp commented on lib/authentication/presentation/pages/sign_up_page.dart
> +                        height: size.height * 0.15,
I'm not a fan of this code. It looks weird on small devices, like too much height. I think if we only provide the width and let the height adjust by the aspect ratio of the image should work better. Let me know if this doesn't work but I think should work better

2023-11-22 18:11 UTC, yarn-rp approved these changes

2023-11-22 18:16 UTC, merged